name: Deploy to FTP/FTPS
on:
  #push:
  workflow_dispatch:
jobs:
  Deploy-FTP-FTPS:
    runs-on: ubuntu-latest
    steps:
      - name: Initializing vscode2npp-theme-converter repository
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Cleaning up files and folders we do not want to upload
        run: |
          rm -rf './.git'
          rm -rf './.gitattributes'
          rm -rf './.github'
          rm -rf './.gitignore'

      - name: Deploying to FTP/FTPS Server
        # https://github.com/SamKirkland/FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          protocol: ftps
          server: ${{ secrets.SYNOLOGY_SERVER_HOSTNAME }}
          port: ${{ secrets.SYNOLOGY_SERVER_PORT_FTPS }}
          username: ${{ secrets.SYNOLOGY_SERVER_USERNAME }}
          password: ${{ secrets.SYNOLOGY_SERVER_PASSWORD }}
          local-dir: './'
          server-dir: '/web/vscode2npp-theme-converter/'
