name: Deploy to SFTP
on:
  #push:
  workflow_dispatch:
jobs:
  Deploy-FTP-FTPS:
    runs-on: ubuntu-latest
    steps:
      - name: Initializing vscode2npp-theme-converter repository
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Cleaning up files and folders we do not want to upload
        run: |
          rm -rf './.git'
          rm -rf './.gitattributes'
          rm -rf './.github'
          rm -rf './.gitignore'

      - name: Deploying to SFTP Server
        # https://github.com/marketplace/actions/sftp-uploader
        uses: wangyucode/sftp-upload-action@v2.0.4
        with:
          host: ${{ secrets.SYNOLOGY_SERVER_HOSTNAME }}
          port: ${{ secrets.SYNOLOGY_SERVER_PORT_SFTP }}
          username: ${{ secrets.SYNOLOGY_SERVER_USERNAME }}
          password: ${{ secrets.SYNOLOGY_SERVER_PASSWORD }}
          localDir: './'
          remoteDir: '/web/vscode2npp-theme-converter/'
